### ISSUE TITLE
kudos

### ISSUE THREAD

**Issue by ghost** [Jezda1337/distro-hub#1]
Hi community: distro-hub, how are you all? Very cool project, I'll see how to help ^^. What are the ways to help here?

**Comment by Jezda1337** [comment]
Hey @nichdemos  I'm happy to hear that you are interested in my project, but I want to clarify that this is only a side project that I worked on during my free time. My original idea was to create an alternative to the DistroWatch app, but to do that, I need to add a lot more information and features to this application. Currently, there are many distributions and their related information that are missing. However, I hope that this project will eventually become a real alternative to DistroWatch as I had initially planned. I haven't yet figured out a contribution plan, but I welcome you to review the project and make suggestions for additions or corrections in the code, or anything else that you think can help improve the project.

**Comment by ghost** [comment]
Hi @Jezda1337, how are you?

> I'm happy to hear that you are interested in my project, but I want to clarify that this is only a side project that I worked on during my free time. 

thanks for comment.

> My original idea was to create an alternative to the DistroWatch app, but to do that, I need to add a lot more information and features to this application. 

I can help with that.

>  Currently, there are many distributions and their related information that are missing. However, I hope that this project will eventually become a real alternative to DistroWatch as I had initially planned. I haven't yet figured out a contribution plan, but I welcome you to review the project and make suggestions for additions or corrections in the code, or anything else that you think can help improve the project.

There is a new communications protocol called nostr, and I think we can use nostr to send and receive custom json messages. The advantage of the protocol is that it works like json, and I think we can make a decentralized distrowatch version with nostr.

***What do you think of the idea of a decentralized website for information from any distro that is somehow permanent?***

**Comment by Jezda1337** [comment]
What problem nostr solve for this project? I didn't heard about the nostr before.

**Comment by ghost** [comment]
Hi @Jezda1337, how are you?

> What problem nostr solve for this project?  I didn't heard about the nostr before.

Please see this: [distro-hub+nostr?](https://github.com/Jezda1337/distro-hub/issues/4): I created a issue that talks in detail about the advantages and disadvantages of the nostr network protocol. In addition to the distr-hub problems that the nostr network protocol can solve.

**Comment by ghost** [comment]
Hi @Jezda1337, how are you? thanks for comment here: [distro-hub+nostr?](https://github.com/Jezda1337/distro-hub/issues/4) and here!
