### ISSUE TITLE
 link to distro-torrent in distro-hub?

### ISSUE THREAD

**Issue by ghost** [Jezda1337/distro-hub#2]
Hi @Jezda1337, how are you?

Would it be possible to add the [fosstorrents](https://fosstorrents.com/) torrent iso link in distro-hub?

**Comment by Jezda1337** [comment]
DistoHub only supports Linux operating systems. Is FossTorrents a type of Linux distribution? It seems like a superior version of DistroHub.

**Comment by ghost** [comment]
Hi @Jezda1337, how are you? (thanks for comment here.)

>  DistoHub only supports Linux operating systems. 

true.

> Is FossTorrents a type of Linux distribution? It seems like a superior version of DistroHub.

No. FossTorrents is a website that indexes torrent files from Linux distributions. Please see this: [distro-hub+ api fosstorrent?](https://github.com/Jezda1337/distro-hub/issues/5): I created a issue that talks in detail about the advantages and disadvantages of the api(fosstorrent) in distro-hub. In addition to the distr-hub problems that the api(foss-torrent) can solve.

**Comment by Jezda1337** [comment]
Hey @nichdemos Initially, I planned to develop an application that would consist of various distribution profiles. The profiles would be created and maintained by the distribution owners themselves to ensure that the information provided is accurate. At first, I thought of scraping data from DistroWatch to populate the profiles, but I realized that would make DistroHub a mere replica of DistroWatch, so I decided against it. Currently, the app is still in development and not yet finished. I'm considering moving to another tech stack, possibly Astro and Go, and I'm open to contributions.

**Comment by ghost** [comment]
Hi @Jezda1337, thanks again for comment here!

> I'm considering moving to another tech stack, possibly Astro and Go, and I'm open to contributions.

great idea! Please comment here too: [distro-hub+ api fosstorrent?](https://github.com/Jezda1337/distro-hub/issues/5)

**Comment by ghost** [comment]
@Jezda1337 thanks for feedback here!
