### ISSUE TITLE
can I share this project with my developer friends?

### ISSUE THREAD

**Issue by ghost** [Jezda1337/distro-hub#3]
Hi @Jezda1337, how are you?

Can I share this project with my developer friends? Is there any image or trademark rights in this open source project that restrict the dissemination and promotion of this project?

***I await any response to this question.***

**Comment by Jezda1337** [comment]
Yes, of course; all of it is open-source.

**Comment by ghost** [comment]
Hi @Jezda1337, thanks for comment. I close a issue here.
