### ISSUE TITLE
distro-hub+nostr?

### ISSUE THREAD

**Issue by ghost** [Jezda1337/distro-hub#4]
Hi @Jezda1337, how are you?

I would like to discuss here the implementation of a network protocol in the distro-hub.

***what is nostr?***
It is a new communication protocol in the same way as http.
- But the difference between nostr and http is that http is just a file formatted as html and text. 
- In the case of the nostr network protocol, the file is a json. 
- But nostr(it is generally used for social media [but you can use it for many things, including managing websites or decentralized systems]).

***Pros:***
- You can use nostr(protocol) as a messaging service to inform developers about real-time website updates.
- Something I noticed in every open source project is having hosting to maintain. nostr can solve this problem as it can maintain decentralized hosting. 
   - This means you don't need to pay for DNS or hosting, just have a simple html, css, js file and everything is hosted.
- There are distrowatch APIs that we can use and then always keep the initial one constantly updated.
   - In this initial scenario, we would have the distro-hub as serverless (that is: working without hosting, DNS and using third-party APIs to inform about Linux distros)
- Decentralized, automatically generated text or HTML file
   - My general idea when using nostr would be to decentralize distro-hub hosting so that we only worry about indexing old versions of distro-hub and keeping the current version running.
   - The site would not be hacked or crashed as it is a self-generated text and html file sent in a decentralized manner

***Cons:***
- But if you want to control everything, you would have to have hosting and DNS for that. 
   - As for the cost of keeping the server running, perhaps we can think about creating a community of users to donate some cash resources towards this.
- The disadvantage of nostr is that it is serverless.
   - This means that there is some server running and this server has some cost to run. For example, the only problem here is that in nostr (there would have to be a server running for the protocol to work).
   - The term 'serverless' is somewhat misleading, as there are still servers providing these backend services, but all of the server space and infrastructure concerns are handled by the vendor.
   - Serverless means that the developers can do their work without having to worry about servers at all.
  - There are public servers, but they can go down or be hacked. What is free is only the hosting of simple texts and files, not complex management pages. This is what I said earlier in this session: " Decentralized, automatically generated text or HTML file". In other words, it would only make sense if we used the nostr network to host simple text and html pages to inform users of the linux distro with some api that lists this. Or if we are going to keep the server running ourselves. 
  - Depending on the suppliers of the nostr network, there are few, and the few that exist are limited. 
  - Some providers only include html and text for decentralized hosting but do not allow any control
- Framework serverless
   - Even though nostr frameworks exist, they are still not complete and feature-rich.
- This allows anyone to post links about distros on the distro-hub website without worrying about the site going down or being hacked.
  - But it would have to have a maintenance cost to do so. 

***What do you think of the idea here?***

**Comment by Jezda1337** [comment]
@nichdemos 
I appreciate you clarifying everything for me, but to be honest, I'm not interested in using the tool you mentioned. I prefer to have complete control over my projects, so if I were to use it, I would want to cover everything from the server to the database and beyond. In the near future, I plan to redesign the application to include more options and information related to a particular distribution. I will be using standard technology, so it won't be decentralized (although I may also handle hosting), but unfortunately, I don't have time to work on this project right now. I plan to resume working on it at the beginning of next year.

**Comment by ghost** [comment]
Hi @Jezda1337, how are you?

thanks for comment here!
