### ISSUE TITLE
distro-hub+ api fosstorrent?

### ISSUE THREAD

**Issue by ghost** [Jezda1337/distro-hub#5]
Hi @Jezda1337, how are you?

I would like to discuss here the implementation of a api(foss-torrent) in the distro-hub.

## Idea
***Pros***
- Automated process: We can take the information from the available linux distros in FOSSTorrent and send it to the distrohub, or perhaps use one of their APIs to update the linux distros in the distro-hub.
- Automated process again: there is no need to manually enter information about a Linux distro.

***Cons***
- Less privacy: we have no control over a third-party service
- Less privacy again: foss-torrent monitors who downloaded the torrent file, it's good for marketing and bad for privacy

## Context

**IMG**
The image I put in the 'context' topic is illustrative, but it demonstrates the information from the outsourced api in the distro-hub

url: `https://distro-hub.radoje.dev/distro/pop_os`

![image](https://github.com/Jezda1337/distro-hub/assets/154566915/32e8c91b-27d1-4349-be10-51cfbbe6eb3f)

***What do you think of this idea - taking information from available linux distros and sending it to distrohub, or perhaps using one of your APIs to update linux distros in distro-hub?***

**Comment by Jezda1337** [comment]
Hey @nichdemos
As I mentioned earlier, my initial idea was to request developers of different Linux distributions to add their data to DistroHub. While scraping data from DistroWatch or any other similar platform is possible, it defeats the purpose of creating a central hub for all Linux distributions. One way to collect data is by reaching out to developers via email and asking them to fill out a form. While I understand that this approach may bother some people, it is a necessary step to gather enough data about various Linux distributions. Once we have a decent number of distributions and users on DistroHub, I am confident that people will start sending requests and emails to include their own distributions

**Comment by ghost** [comment]
Hi @Jezda1337, thanks for feedback here again!
